#!/bin/bash
  
# Clear the console before starting
  clear

# Give permissions to the scripts
  chmod 755 scripts/*

# Create bold and normal types of letter
  bold=`tput bold`
  normal=`tput sgr0`

# Create a variable to store the version 
  version=0.1 

# Introducing test 
  echo
  echo "${bold}-----------------------------------"
  echo " BroadcomCM kernel auto-maker menu"
  echo "-----------------------------------"
  echo "${normal} Version $version"
  echo
  echo

# First question:
  echo "${bold} Which device you would like to build?${normal} Choose a letter:"

# Answers:
  echo "   a. Cooperve"
  echo "   b. Luisa"
  echo "   c. Tassve"
  echo "   d. Totoro"
  echo
  echo "   x. Exit"
  echo "   r. Restart"

# Read the letter the user gives
  echo 
  read enterLetter

# Cooperve
  if [ "$enterLetter" == "a" ]
    then
      scripts/cooperve_build

# Luisa
  elif [ "$enterLetter" == "b" ]
    then
      scripts/luisa_build

# Tassve
  elif [ "$enterLetter" == "c" ]
    then
      scripts/tassve_build

# Totoro
  elif [ "$enterLetter" == "d" ]
    then
      scripts/totoro_build

# Restart
  elif [ "$enterLetter" == "r" ]
    then
      ./Menu

# Exit
  elif [ "$enterLetter" == "x" ]
    then
      exit 0

# Other choice
  else 
    echo "Invalid option"
    continue
  
  fi
