#!/bin/bash

#    BroadcomCM kernel auto-maker menu - ./menu
#    Copyright (C) 2013  BroadcomCM Team
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Clear the console before starting
  clear

# Give permissions to the scripts
  chmod 755 scripts/*

# if firstboot file is not created launch toolchain set
if test -e .fboot
then
   echo "Toolchain already set, going away..."
else
   echo "Launching toolchain set..."
   echo "Press enter to continue"
   read enterPress
   scripts/set_toolchain_path
   touch .fboot
   echo DO NOT DELETE THIS FILE!!! > .fboot
   chmod 440 .fboot
fi

# Clear the console before starting
  clear

# Create bold and normal types of letter
  export t_bold=`tput bold`
  export t_normal=`tput sgr0`

# Create a variable to store the version 
  export version=0.1 

# Introducing test 
  echo
  echo "${t_bold}-----------------------------------"
  echo " BroadcomCM kernel auto-maker menu"
  echo "-----------------------------------"
  echo "${t_normal} Version $version"
  echo
  echo

# First question:
  echo "${t_bold} Which device you would like to build?${t_normal} Choose a letter:"

# Answers:
  echo "   a. Cooperve"
  echo "   b. Luisa"
  echo "   c. Tassve"
  echo "   d. Totoro"
  echo
  echo "   x. Exit"
  echo "   r. Restart"

# Read the letter the user gives
  echo 
  read enterLetter

# Cooperve
  if [ "$enterLetter" == "a" ]
    then
      export KBUILD_BCM_MENU=cooperve
      scripts/prepare_device

# Luisa
  elif [ "$enterLetter" == "b" ]
    then
      export KBUILD_BCM_MENU=luisa
      scripts/prepare_device

# Tassve
  elif [ "$enterLetter" == "c" ]
    then
      export KBUILD_BCM_MENU=tassve
      scripts/prepare_device

# Totoro
  elif [ "$enterLetter" == "d" ]
    then
      export KBUILD_BCM_MENU=totoro
      scripts/prepare_device

# Restart
  elif [ "$enterLetter" == "r" ]
    then
      ./menu

# Exit
  elif [ "$enterLetter" == "x" ]
    then
      exit 0

# Other choice
  else 
    echo "Invalid option"
    continue
  
  fi
