#!/bin/bash

############################################################################
#
# Copyright (c) 2012 - dsixda (dislam@rocketmail.com)
#
# Android Kitchen is 100% free.  This script file is intended for personal
# and/or educational use only.  It may not be duplicated for monetary
# benefit or any other purpose without the permission of the developer.
#
############################################################################

#
# This script has one optional parameter:
#
# $1 = folder containing boot.img
#

if [ -e .check.img ] 
then

  dec_offset=`scripts/get_boot_img_page_size`

  if [ "$dec_offset" != "" ]
  then

    if [ "$dec_offset" == "0" ]
    then
      echo "Error: kernel offset (page size) is 0"
      exit 1
    fi

    echo "Kernel found at offset $dec_offset in boot.img"

  else
    echo "Error: kernel offset (page size) not found in boot.img!"
    exit 1
  fi

else
  echo "check.img not found, be sure you did not delete it!"
  cd ../
  exit 1
fi

