#!/bin/bash

# Clear terminal
clear

# Create bold and normal types of letter
bold=`tput bold`
normal=`tput sgr0`

# Write wich device we choose
echo "${bold} Your device is $KBUILD_BCM_MENU ${normal}"

clear

scripts/toolchain_path

# Moving to correct path
cd ../
cd common

# Make clean
echo
echo "${bold} MAKE CLEAN...${normal}"
echo
  make clean

# Make distclean
echo
echo "${bold} MAKE DISTCLEAN...${normal}"
echo
  make distclean
  
# Make cyanogenmod_device_defconfig
echo
echo "${bold} SELECTING THE DEFCONFIG --> cyanogenmod_$KBUILD_BCM_MENU'_defconfig'${normal}"
echo
  make cyanogenmod_$KBUILD_BCM_MENU'_defconfig'

# Make menuconfig
echo
echo "${bold} LAUNCHING MENUCONFIG${normal}"
echo
  make menuconfig

# WIP, do not close terminal
read entertodddols
