#!/bin/bash

############################################################################
#
# Copyright (c) 2011 - dsixda (dislam@rocketmail.com)
#
# Android Kitchen is 100% free.  This script file is intended for personal
# and/or educational use only.  It may not be duplicated for monetary
# benefit or any other purpose without the permission of the developer.
#
############################################################################

page_size=`od -A n -D -j 36 -N 4 .check.img | sed 's/ //g'`

echo $page_size


