#!/bin/bash
 
#    BroadcomCM kernel auto-maker menu - scripts/load_new_config
#    Copyright (C) 2013  Team BroadcomCM
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>. 
  
# Clear the console
  clear

# Introducing text 
  echo
  echo "${t_bold}-----------------------------------"
  echo " BroadcomCM kernel auto-maker menu"
  echo "-----------------------------------"
  echo "${t_normal} Version $version"
  echo

# Insert the config name and test if existing
  echo "${t_bold} Type the name of the config (including _defconfig if the name includes that)${t_normal}"
  echo " The config must be located in arch/arm/configs"
  echo
  read enterConfig

  # Create a variable that stores command for see if config is existing
  FN=$(find arch/arm/configs/$enterConfig)

  # If the variable returns same as config path then the config is ok
  if [ "$FN" == "arch/arm/configs/$enterConfig" ]
    then

      # Make the custom config
      echo
      echo "${t_bold} SELECTING THE DEFCONFIG --> $enterConfig ${t_normal}"
      echo
      make $enterConfig -j`grep processor /proc/cpuinfo | wc -l`

      # Back with new defconfig
      echo
      echo "${t_bold} New config made, press enter to continue... ${t_normal}"

      # Change defconfig variable to the new one
      export defconfig=$enterConfig

      # Back to menu
      read enterKey
      ../../BCMKAMM/scripts/tools_menu

  else

    # Error on defconfig (does not exist)
    echo "Config does not exist, please check the name and retry"
    read enterKey
    ../../BCMKAMM/scripts/load_new_defconfig

  fi
