#!/bin/bash

#    BroadcomCM kernel auto-maker menu - scripts/make_menuconfig
#    Copyright (C) 2013  Team BroadcomCM
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Make menuconfig
  make menuconfig -j`grep processor /proc/cpuinfo | wc -l`
  

# OPTION A - Simple menuconfig
  if [ "$MENUCONFIG" == "a" ]
   then
    echo "${t_bold} New configuration saved,${t_normal} press enter to continue..."
    read enterkey

    # Come back to menu
    ../../BCMKAMM/scripts/tools_menu
  fi


# OPTION B - Save on original defconfig file
  if [ "$MENUCONFIG" == "b" ]
   then    
      # Copy the modded .config
      cp .config arch/arm/configs/$defconfig
      echo "${t_bold} Old defconfig has been replaced with new one${t_normal}"
      echo " Press enter to continue..."
      read enterKey
      
      # Come back to menu
      ../../BCMKAMM/scripts/tools_menu
   fi


# OPTION C - Create new defconfig file
  if [ "$MENUCONFIG" == "c" ]
    then
      # Enter the config name
      echo "${t_bold} Enter your new defconfig name...${t_normal} (excluding _defconfig)"
      read enterName

      # If nothing on name
      if [ "$enterName" == "" ]
        then
        echo "${t_bold} You must choose a name for your defconfig${t_normal}"
        echo " Press enter to retry..."
        read enterKey
        
        # Restart script
        ../../BCMKAMM/scripts/tools_menu

      # If there is name
      else

        # Copy the file
        cp .config arch/arm/configs/$enterName''_defconfig
        echo "${t_bold} Config saved,${t_normal} press enter to continue"
        read enterKey

        # Come back to menu
        ../../BCMKAMM/scripts/tools_menu
      
      fi
  fi
