#!/bin/bash

#    BroadcomCM kernel auto-maker menu - scripts/tools_menu
#    Copyright (C) 2013  Team BroadcomCM
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Make menuconfig
  make menuconfig -j`grep processor /proc/cpuinfo | wc -l`
  

# OPTION A - Simple menuconfig
  if [ "$Option" == "a" ]
   then
    echo "New configuration saved, press enter to continue..."
    read enterkey

    # Come back to menu
    ../../BCMKAMM/scripts/tools_menu
  fi


# OPTION B - Save on original defconfig file
  if [ "$Option" == "b" ]
   then    
      # Copy the modded .config
      cp .config arch/arm/configs/cyanogenmod_$KBUILD_BCM_MENU''_defconfig
      echo "Old cyanogenmod_$KBUILD_BCM_MENU""_defconfig has been replaced with new one"
      echo "Press enter to continue..."
      read enterKey
      
      # Come back to menu
      ../../BCMKAMM/scripts/tools_menu
   fi


# OPTION C - Create new defconfig file
  if [ "$Option" == "c" ]
    then
      # Enter the config name
      echo "Enter your new defconfig name... (excluding _defconfig)"
      read enterName

      # If nothing on name
      if [ "$enterName" == "" ]
        then
        echo "You must choose a name for your defconfig"
        echo "Press enter to retry..."
        read enterKey
        
        # Restart script
        ../../BCMKAMM/scripts/tools_menu

      # If there is name
      else

        # Copy the file
        cp .config arch/arm/configs/$enterName''_defconfig
        echo "Config saved, press enter to continue"
        read enterKey

        # Come back to menu
        ../../BCMKAMM/scripts/tools_menu
      
      fi
fi
