#!/bin/bash

#    BroadcomCM kernel auto-maker menu - scripts/prepare_device
#    Copyright (C) 2013  BroadcomCM Team
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Clear terminal
clear

# Create bold and normal types of letter
bold=`tput bold`
normal=`tput sgr0`

# Write wich device we choose
echo "${bold} Your device is $KBUILD_BCM_MENU ${normal}"

clear

scripts/toolchain_path

# Moving to correct path
cd ../
cd common

# Make clean
echo
echo "${bold} MAKE CLEAN...${normal}"
echo
  make clean

# Make distclean
echo
echo "${bold} MAKE DISTCLEAN...${normal}"
echo
  make distclean
  
# Make cyanogenmod_device_defconfig
echo
echo "${bold} SELECTING THE DEFCONFIG --> cyanogenmod_$KBUILD_BCM_MENU'_defconfig'${normal}"
echo
  make cyanogenmod_$KBUILD_BCM_MENU'_defconfig'

# Press enter and go to the build menu
echo "${bold} Press enter to go to build menu${normal}"

read enterKey

scripts/tools_menu
