#!/bin/bash

#    BroadcomCM kernel auto-maker menu - scripts/prepare_device
#    Copyright (C) 2013  BroadcomCM Team
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Clear terminal
clear

# Write wich device we choose
echo "${t_bold} Your device is $KBUILD_BCM_MENU ${t_normal}"
echo
echo "${t_bold} Defconfig is cyanogen_$KBUILD_BCM_MENU''_defconfig ${t_normal}"

clear

# Source the exports
source scripts/toolchain_path

# Add a defconfig variable
export defconfig=cyanogenmod_$KBUILD_BCM_MENU''_defconfig

# Moving to correct path
cd ..
cd kernel

# Renaming modules dir
echo
echo " Renaming modules dir from 'modules_$KBUILD_BCM_MENU' to 'modules'"
mv modules_$KBUILD_BCM_MENU modules
cd common

# Make clean
echo
echo "${t_bold} MAKE CLEAN...${t_normal}"
echo
  make clean -j`grep processor /proc/cpuinfo | wc -l`

# Make distclean
echo
echo "${t_bold} MAKE DISTCLEAN...${t_normal}"
echo
  make distclean -j`grep processor /proc/cpuinfo | wc -l`
  
# Make cyanogenmod_device_defconfig
echo
echo "${t_bold} SELECTING THE DEFCONFIG --> $defconfig${t_normal}"
echo
  make $defconfig -j`grep processor /proc/cpuinfo | wc -l`

# Press enter and go to the build menu
echo
echo "${t_bold} Press enter to go to build menu${t_normal}"

read enterKey

../../BCMKAMM/scripts/tools_menu
