#!/bin/bash

clear

# Give path to toolchain and various exports
echo
echo " Where is your toolchain located?"
echo " Normally it should be in '~/CodeSourcery/Sourcery_G++_Lite/bin/arm-none-eabi-'"
echo
echo " Enter the full path, without "" or '' and don't forget to add arm-eabi- or "
echo " arm-none-eabi- according to your toolchain binaries name."
echo
echo " Do not enter anything if your path is"
echo " '~/CodeSourcery/Sourcery_G++_Lite/bin/arm-none-eabi-'"
echo
echo Insert here:

read enterPath

# if enterPath is inserted set the path inserted
if [ "$enterPath" == "*" ]
then
  # if the find is equal to the path so the toolchain is ok
  LD=$(find $enterPath'ld')
  if [ "$LD" == "$enterPath'ld'" ]
  then
     echo "Toolchain path is ok and has been set"
     # create the toolchain_path script
     echo -e "
#!/bin/bash \n
# DO NOT DELETE THIS FILE!!! \n
export ARCH=arm \n 
export CROSS_COMPILE='$enterPath'" > scripts/toolchain_path
  else
     # if get some error or toolchain path not correct restart the script
     echo "Toolchain path is not ok, please retry"
     read enterKey
     scripts/set_toolchain_path
  fi
# if enterPath is not inserted use the default path
else
   # if the find is equal to the path so the toolchain is ok
  LD2=$(find ~/CodeSourcery/Sourcery_G++_Lite/bin/arm-none-eabi-ld)
  if [ "$LD2" == "~/CodeSourcery/Sourcery_G++_Lite/bin/arm-none-eabi-ld"]]
  then
     echo "Toolchain path is ok and has been set"
     # create the toolchain_path script
     echo -e "
#!/bin/bash \n
# DO NOT DELETE THIS FILE!!! \n
export ARCH=arm \n
export CROSS_COMPILE='~/CodeSourcery/Sourcery_G++_Lite/bin/arm-none-eabi-'" > scripts/toolchain_path
  else
     # if get some error or toolchain path not correct restart the script
     echo "Toolchain path is not ok, please retry"
     read enterKey
     scripts/set_toolchain_path
  fi
fi

./menu
