#!/bin/bash

#    BroadcomCM kernel auto-maker menu - scripts/set_toolchain_path
#    Copyright (C) 2013  Matteo Lo Piccolo (lopicl.00@gmail.com)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

clear

# Create bold and normal types of letter
export t_bold=`tput bold`
export t_normal=`tput sgr0`

# Introducing test 
  echo
  echo "${t_bold}-----------------------------------"
  echo " BroadcomCM kernel auto-maker menu"
  echo "-----------------------------------"
  echo "${t_normal} Version $version"
  echo
  echo

# Give path to toolchain and various exports
echo "${t_bold} Where is your toolchain located?${t_normal}"
echo " Normally it should be in /home/$USER/CodeSourcery/Sourcery_G++_Lite/bin/arm-none-eabi-"
echo
echo " Enter the full path (replace '~/' with '/home/$USER/ and don't forget to add "
echo " arm-eabi- or arm-none-eabi- according to your toolchain binaries name."
echo
echo " Insert here:"

read enterPath

# Store a variable LD with a file inside toolchain
  LD=$(find $enterPath''ld)

# Create another variable that stores the last one
  ELD=$(echo $LD)

# If the find is equal to the path the toolchain is ok
if [ "$ELD" == "$enterPath"ld"" ]
  then  
    echo
    echo " Press enter to start building the kernel..."    

    # Create the toolchain_path script
    echo -e "#!/bin/bash \n
    # DO NOT DELETE THIS FILE!!! \n
    cd ../
    cd Kernel/common \n 
    export ARCH=arm \n 
    export CROSS_COMPILE=$enterPath \n
    echo ARCH=arm
    echo CROSS_COMPILE=/home/bieltv3/CodeSourcery/Sourcery_G++_Lite/bin/arm-none-eabi- "> scripts/toolchain_path

else
    # If get some error or toolchain path not correct restart the script
    echo "${t_bold} Toolchain path is not correct, please retry${t_normal}"
    read enterKey
    scripts/set_toolchain_path

fi

# Give permissions to the script created
chmod 777 scripts/toolchain_path
