#!/bin/bash

#    BroadcomCM kernel auto-maker menu - scripts/tools_menu
#    Copyright (C) 2013  Team BroadcomCM
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Clear the console
  clear

# Menucofnig variables
  export Option=""
  export save_new_config=0
  export input_config_name=0

# Introducing test 
  echo
  echo "${t_bold}-----------------------------------"
  echo " BroadcomCM kernel auto-maker menu"
  echo "-----------------------------------"
  echo "${t_normal} Version $version"
  echo
  echo " Device selected is $KBUILD_BCM_MENU"
  echo
  echo

# Question:
  echo "${t_bold} What you want to do?${t_normal} Choose a letter:"

# Options:
  echo "   a. Make Menuconfig"
  echo "   b. Make Menuconfig with saving new config to cyanogenmod_$KBUILD_BCM_MENU''_defconfig"
  echo "   c. Make Menuconfig with saving new config to input name"
  echo
  echo "   d. Load another defconfig"
  echo
  echo "   e. Make clean"
  echo "   f. Make distclean"
  echo
  echo "   g. Make kernel zImage"
  echo "   h. Make kernel zImage + boot.img with common ramdisk"
  echo "   i. Make kernel zImage + boot.img with yours ramdisk"
  echo
  echo "   j. Exit"
  echo "   k. Restart"

# Read letter user gives
  read enterLetter

# OPTION A
  if [ "$enterLetter" == "a" ]
    then

      Option="a"

      # Start menuconfig scripts
      ../../BCMKAMM/scripts/make_menuconfig


# OPTION B
  elif [ "$enterLetter" == "b" ]
    then

      Option="b"
      
      # Start menuconfig scripts
      ../../BCMKAMM/scripts/make_menuconfig


# OPTION C
  elif [ "$enterLetter" == "c" ]
    then

       Option="c"
      
      # Start menuconfig scripts
      ../../BCMKAMM/scripts/make_menuconfig


# OPTION D
  elif [ "$enterLetter" == "d" ]
    then
      ../../BCMKAMM/scripts/load_new_config

  elif [ "$enterLetter" == "e" ]
    then
      echo "Making clean..."
      make clean -j`grep processor /proc/cpuinfo | wc -l`
      echo "Press enter to continue"
      read enterKey6
      ../../BCMKAMM/scripts/tools_menu

  elif [ "$enterLetter" == "f" ]
    then
      echo "Making dist clean..."
      make distclean -j`grep processor /proc/cpuinfo | wc -l`
      echo "Press enter to continue"
      read enterKey7
      ../../BCMKAMM/scripts/tools_menu

  elif [ "$enterLetter" == "g" ]
    then
      echo "Starting build of kernel..."
      echo "Press enter to continue..."
      read enterKey8
      make
      ../../BCMKAMM/scripts/tools_menu

  elif [ "$enterLetter" == "h" ]
    then
      echo ZONE WORK IN PROGRESS...
      read enterKey9
      ../../BCMKAMM/scripts/tools_menu

  elif [ "$enterLetter" == "i" ]
    then
      echo ZONE WORK IN PROGRESS...
      read enterKey10
      ../../BCMKAMM/scripts/tools_menu

  elif [ "$enterLetter" == "j" ]
    then
      ../../BCMKAMM/scripts/exit_script

  elif [ "$enterLetter" == "k" ]
    then
      ../../BCMKAMM/menu

fi
