#!/bin/bash

#    BroadcomCM kernel auto-maker menu - scripts/tools_menu
#    Copyright (C) 2013  Team BroadcomCM
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Clear the console
  clear

# Introducing text 
  echo
  echo "${t_bold}-----------------------------------"
  echo " BroadcomCM kernel auto-maker menu"
  echo "-----------------------------------"
  echo "${t_normal} Version $version"
  echo
  echo " $defconfig is selected"
  echo

# Question:
  echo "${t_bold} What you want to do?${t_normal} Choose a letter:"

# Options:
  echo "   a. Make Menuconfig"
  echo "   b. Make Menuconfig replacing old $defconfig with new one"
  echo "   c. Make Menuconfig with saving new config to input name"
  echo
  echo "   d. Load another defconfig"
  echo
  echo "   e. Make clean"
  echo "   f. Make distclean"
  echo
  echo "   g. Make kernel zImage"
  echo "   h. Make kernel zImage + boot.img with common ramdisk"
  echo "   i. Make kernel zImage + boot.img with yours ramdisk"
  echo
  echo "   x. Exit"
  echo "   r. Restart"

# Read letter user gives
  read enterLetter

# OPTION A - MENUCONFIG
  if [ "$enterLetter" == "a" ]
    then

      export MENUCONFIG="a"

      # Start menuconfig script
      ../../BCMKAMM/scripts/make_menuconfig


# OPTION B - MENUCONFIG + SAVE NEW
  elif [ "$enterLetter" == "b" ]
    then

      export MENUCONFIG="b"
      
      # Start menuconfig script
      ../../BCMKAMM/scripts/make_menuconfig


# OPTION C - MENUCONFIG + SAVE ANOTHER NAME
  elif [ "$enterLetter" == "c" ]
    then

       export MENUCONFIG="c"
      
      # Start menuconfig script
      ../../BCMKAMM/scripts/make_menuconfig


# OPTION D - LOAD ANOTHER CONFIG
  elif [ "$enterLetter" == "d" ]
    then

      ../../BCMKAMM/scripts/load_new_config

# OPTION E - MAKE CLEAN
  elif [ "$enterLetter" == "e" ]
    then

      export MAKECLEAN="a"

      # Start make clean script
      ../../BCMKAMM/scripts/make_clean

# OPTION F - MAKE DISTCLEAN
  elif [ "$enterLetter" == "f" ]
    then

      export MAKECLEAN="b"

      # Start make clean script
      ../../BCMKAMM/scripts/make_clean

# OPTION G - MAKE ZIMAGE
  elif [ "$enterLetter" == "g" ]
    then

      # Start ZIMAGE script
      ../../BCMKAMM/scripts/make_kernel

# OPTION H - MAKE ZIMAGE + BOOTIMG (COMMON RAMDISK)
  elif [ "$enterLetter" == "h" ]
    then
      export RAMDISK="a"

      # Start ZIMAGE script
      ../../BCMKAMM/scripts/make_kernel

# OPTION I - MAKE ZIMAGE + BOOTIMG (USER RAMDISK)
  elif [ "$enterLetter" == "i" ]
    then
      export RAMDISK="b"

      # Start ZIMAGE script
      ../../BCMKAMM/scripts/make_kernel

# OPTION X - EXIT
  elif [ "$enterLetter" == "x" ]
    then
      ../../BCMKAMM/scripts/exit_script

# OPTION R - RESTART
  elif [ "$enterLetter" == "r" ]
    then
      ../../BCMKAMM/menu

# WRONG OPTION
  else
    echo "Wrong command, press enter to try again"
    read enterKey
    ../../BCMKAMM/scripts/tools_menu

fi
